### PR TITLE
Replace opencde

### PR DESCRIPTION
**Pull request by ykulbak**
Please review and merge. 

After merging please also merge the release branch with master to ensure both are in sync.

### CODE REVIEW

**Review by GeorgDangl — CHANGES_REQUESTED** [review]
We still mention the term ‚OpenCDE‘ quite often in the text, e.g. in the Header at the very start and other texts.

**Comment by pasi-paasiala** [comment]
The target branch is wrong, or why are there two commits by Jon Anders?

**Comment by ykulbak** [comment]
> We still mention the term ‚OpenCDE‘ quite often in the text, e.g. in the Header at the very start and other texts.

There's no requirement to remove OpenCDE from the spec. We were only requested to remove the terms from the API so that implementers might not need to change their APIs in a few years.

**Comment by ykulbak** [comment]
> The target branch is wrong, or why are there two commits by Jon Anders?

Why is that target branch wrong? 
The two commits from Jon Andres are there because I've merged with the master branch. These change should have come through when Georg and I were creating the release.

**Review by GeorgDangl — APPROVED** [review]

**Pull request merged**
